services:
  db:
    image: postgres:15-alpine
    container_name: students-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - student-net

  liquibase:
    image: liquibase/liquibase:latest
    container_name: students-liquibase-migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - LIQUIBASE_COMMAND_USERNAME=${POSTGRES_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${POSTGRES_PASSWORD}
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog.xml
      - INSTALL_POSTGRESQL_DRIVER=true
    volumes:
      - ./changelog:/liquibase/changelog
      - ./drivers/postgresql.jar:/liquibase/internal/lib/postgresql.jar
    command: ["update"]
    networks:
      - student-net

  app:
    build: .
    container_name: students-fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - student-net

volumes:
  dbdata:

networks:
  student-net:
    driver: bridge